version: '3.6'

services:
    ctesi:
        build: .
        environment:
            DEBUG: 'true'
            LC_ALL: 'C.UTF-8'
            LANG: 'C.UTF-8'
            FLASK_APP: 'ctesi/__init__.py'
            FLASK_DEBUG: 1
        volumes:
            - .:/home/ctesi/ctesi
            - ../cimage-minimal:/home/ctesi/cimage-minimal
            - data:/data
        cap_add:
            - SYS_ADMIN
            - DAC_READ_SEARCH
        tty: true
        stdin_open: true
    flask-readw:
        image: radusuciu/flask-readw
        environment:
          DEBUG: 'true'
          FLASK_DEBUG: 1
          FLASK_ENV: 'development'
          LC_ALL: 'C.UTF-8'
          LANG: 'C.UTF-8'
          FLASK_APP: 'flask_readw/__init__.py'
        volumes:
            - ../flask-readw:/app/flask_readw
            - data:/raw_vault
        tty: true
        stdin_open: true
        ports:
            - target: "5000"
              published: "5001"
    rabbitmq:
        image: rabbitmq
        hostname: rabbitmq
        tty: true
        stdin_open: true
    redis:
        image: redis
        hostname: redis
    nginx:
        image: nginx
        volumes:
            - ./config/nginx.conf:/etc/nginx/ctesi.conf
            - ./ctesi/static:/usr/share/nginx/html/static
        ports:
            - '80:80'
        environment:
            NGINX_HOST: 'localhost'
        command: /bin/bash -c "envsubst '$$NGINX_HOST' < /etc/nginx/ctesi.conf > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
volumes:
    data:
