version: '3.6'

services:
    ctesi:
        environment:
            DEBUG: 'false'
            FLASK_DEBUG: 0
            FLASK_ENV: 'production'
    flask-readw:
        environment:
            DEBUG: 'false'
            FLASK_DEBUG: 0
            FLASK_ENV: 'production'
