flask:
  SECRET_KEY: 'dbasdyasio47kljloi84sRnuaL'
flask-security:
  SECURITY_PASSWORD_SALT: '8CjvYzVZgV8q:ZL#,7R8'
ldap:
  BASE_DN: 'OU=foo,DC=ad,DC=example,DC=com'
  BIND_DN: 'example@example.com'
  BIND_PASSWORD: 'password'
  SEARCH_FILTER: '(sAMAccountName={})'
  URI: 'ldap://ad.example.com'